In [2]:
import pandas as pd

user_data = pd.read_csv("all_user_data_c_50_95.csv")

In [3]:
user_data.drop(user_data.columns[[0]], axis=1, inplace=True)
user_data.head()

    id                          name  editcount  status
0   15                            !!       1540       1
1  228                        !dea4u       6722       0
2  387  "Country" Bushrod Washington       1652       0
3  582                       "Yahia"       1023       0
4  829               $1LENCE D00600D      18642       0

In [4]:
user_data.describe().apply(lambda s: s.apply(lambda x: format(x, 'g')))

                id    editcount       status
count        25993        25993        25993
mean   2.93366e+06      12595.9  0.000269303
std    1.66776e+06      86431.6    0.0164086
min             15         1001            0
25%    1.54103e+06         1511            0
50%    2.93997e+06         2760            0
75%    4.32818e+06         7177            0
max     5.9142e+06  6.81225e+06            1

In [13]:

import os.path
import numpy as np
from trust_score import TrustScore
from sklearn import metrics
from sklearn.linear_model import LinearRegression
import json

y_pred = []
y_test=[]
cou = 0
words = []

for row in user_data.iterrows():
    path = 'user_data_50_95/rev_list_' + str(row[1]['id']) + '-d.json'
    #print(path)
    try:
        with open(path, 'r') as infile:
            data = json.loads(infile.read())
            if len(data) > 0:
                for d in data:
                    del d['next_rev']
                
                print(path)

                graph_for = "longevityRev"

                series = pd.DataFrame(data=data)
                series = series[['pageid', 'timestamp', 'small_text', graph_for]]
                series = series[series.longevityRev >= 0]
                if len(series) > 9:
                    print('User ID: ', str(row[1]['id']))
                    print(series['small_text'])
                    
    except Exception as e:
#         print('error :')
        1+1

user_data_50_95/rev_list_15-d.json
User ID:  15
6                                          [a, are ]
8                                                 []
11     [----, :, <br>, <br>, <br>, <br>, <br>, ----]
12                          []], [[, ]], [[, [[, ]]]
13                                                []
                           ...
345                                            [or ]
346                                         [[[, ]]]
347                                               []
348                                               []
349                                               []
Name: small_text, Length: 253, dtype: object
user_data_50_95/rev_list_228-d.json
User ID:  228
0        []
1        []
2        []
3        []
4        []
5        []
6        []
7        []
8     [Red]
12       []
Name: small_text, dtype: object
user_data_50_95/rev_list_1350-d.json
user_data_50_95/rev_list_1400-d.json
User ID:  1400
0                []
2            [,, B]
3                []
4                []
5             [ Is]
          ...
94               []
95               []
96    [OV,, ut, eh]
97               []
99               []
Name: small_text, Length: 65, dtype: object
user_data_50_95/rev_list_127449-d.json
User ID:  127449
1      ['', '', '', '', '']
2                        []
3                        []
5                        []
6                        []
               ...
252                      []
253                      []
254                      []
255                      []
256                      []
Name: small_text, Length: 211, dtype: object
user_data_50_95/rev_list_127796-d.json
user_data_50_95/rev_list_128146-d.json
user_data_50_95/rev_list_128228-d.json
user_data_50_95/rev_list_457278-d.json
user_data_50_95/rev_list_457398-d.json
user_data_50_95/rev_list_458853-d.json
user_data_50_95/rev_list_459097-d.json
user_data_50_95/rev_list_461032-d.json
User ID:  461032
0                                         []], t,  ,  ]
1                                         []], t,  ,  ]
2     [Ary, Ary, ]], t, It,  , mix, nd, voca, heeg, ...
3                                                    []
5                                                    []
6                                                    []
7                                                    []
8                                                    []
9                                                    []
10                                                   []
Name: small_text, dtype: object
user_data_50_95/rev_list_461935-d.json
user_data_50_95/rev_list_622291-d.json
user_data_50_95/rev_list_624913-d.json
user_data_50_95/rev_list_625193-d.json
user_data_50_95/rev_list_626695-d.json
User ID:  626695
0     [Noi,  Nex, D, Ed, c]
1                        []
2                        []
3                        []
4                        []
5                        []
6                        []
7                      [\n]
8                        []
9                        []
10                       []
11                       []
12                       []
13                   [\n\n]
14                       []
15                       []
16                       []
17                       []
18                       []
19                       []
20                       []
21                       []
22                       []
23                       []
24                       []
25                       []
26                       []
28             [\n, ss, ]]]
29     [\n, \n, \n, \n, \n]
30                       []
31                       []
32                       []
33                    [ark]
34                       []
35                       []
36                       []
37                       []
38                       []
39                     [\n]
40                       []
41                       []
42                       []
43                       []
44                       []
45                       []
46                       []
47                       []
48                       []
49                       []
50                       []
51                       []
52                       []
53                       []
Name: small_text, dtype: object
user_data_50_95/rev_list_627512-d.json
user_data_50_95/rev_list_627634-d.json
user_data_50_95/rev_list_627756-d.json
User ID:  627756
0        [two]
1           []
2          [)]
3         [er]
4           []
5           []
6         [as]
7           []
8           []
9          [e]
10          []
12          []
13          []
14          []
16     [c, we]
17          []
18          []
19          []
20          []
21          []
22          []
23         [d]
24    [T, was]
Name: small_text, dtype: object
user_data_50_95/rev_list_628181-d.json
User ID:  628181
0                                           []
2                                           []
3                                           []
5                                           []
6                                           []
7                                           []
8                                           []
9                                           []
10    [\n , \n , \n , \n , \n , \n , \n , \n ]
11                                          []
12                                         []]
13                                         [e]
14                                         [e]
15                                          []
16                                          []
Name: small_text, dtype: object
user_data_50_95/rev_list_628529-d.json
User ID:  628529
0                                           []]]
1                                             []
2                                       [ , an ]
3                                     [ew , ork]
4                                             []
5                                            []]
6                                            [-]
7                                       [& t,  ]
8                                            [ ]
9                                             []
10                                            []
11                                           [ ]
12                                           [)]
13                                            []
14                                          []]]
15                                            []
16                                        [. L.]
17    [ of ,  ,  ,  ,  ,  ,  ,  of ,  ,  of ,  ]
18                                         [LCO]
19                                            []
20                                            []
21                                         [url]
Name: small_text, dtype: object
user_data_50_95/rev_list_777120-d.json
user_data_50_95/rev_list_777695-d.json
user_data_50_95/rev_list_778833-d.json
user_data_50_95/rev_list_778834-d.json
User ID:  778834
0                               []
1                     [\n\n*, * T]
2            [Irr, \n,  ,  ,  ,  ]
5                              [t]
6                            [ex-]
7                               []
8     [[[, [[, ]], [[, ]], why, e]
9                     [Re, [[, ]]]
10                             [ ]
11                              []
13                              []
14                              []
15                              []
16                              []
Name: small_text, dtype: object
user_data_50_95/rev_list_780365-d.json
User ID:  780365
0                              []
1                              []
2                              []
3                              []
4                              []
5                              []
6                              []
7                              []
8     [i, uper, uted, y [[, an]]]
10                             []
11                             []
12                             []
13                            [m]
14                             []
15                           [--]
16                          [com]
17                             []
18                             []
19                             []
20                             []
21                             []
Name: small_text, dtype: object
user_data_50_95/rev_list_782682-d.json
user_data_50_95/rev_list_784393-d.json
user_data_50_95/rev_list_784644-d.json
user_data_50_95/rev_list_921778-d.json
User ID:  921778
1                    []
2                    []
3                    []
4                    []
5                    []
6                    []
7                    []
8                    []
9                    []
10                   []
11    [\n* , lop, s, e]
13                   []
14                   []
15                   []
16                   []
17             [==, ==]
18                  []]
19                   []
22                   []
23                   []
24                   []
25                   []
26                   []
27              [==, *]
28                  [*]
29                   []
31                   []
34                   []
35                   []
Name: small_text, dtype: object
user_data_50_95/rev_list_921838-d.json
user_data_50_95/rev_list_921928-d.json
user_data_50_95/rev_list_922320-d.json
User ID:  922320
0                                                    []
1                                                    []
2                                                   [K]
3                                                    []
4                                                    []
6                                                    []
9                                                    []
10                                                   []
12                                                   []
13    [h, i, t, p, ', n, i, s,  , i, i, a, not , e, ...
14                                                  [a]
15                                                   []
16                                               [ and]
17                                                   []
18                                                   []
20                                 [ua, ua, ua, ua, ua]
21                                     [[[, ]], [[, ]]]
22                                                   []
23                                               [ and]
24                                               [a, a]
Name: small_text, dtype: object
user_data_50_95/rev_list_923522-d.json
user_data_50_95/rev_list_1077274-d.json
User ID:  1077274
0           []
1           []
2         [\n]
3           []
4           []
5       [2006]
6         [\n]
7           []
8           []
9           []
10        [ne]
11          []
13    [a, ter]
Name: small_text, dtype: object
user_data_50_95/rev_list_1078142-d.json
User ID:  1078142
0                                                 [s, ,]
1                                                     []
3                                               [[[, ]]]
4                                                  [to ]
5                                                     []
                             ...
118                                                 [|M]
119                                                 []]]
122    [ ,  ,  ,  ,  ,  ,  ,  ,  ,  ,  ,  ,  ,  ,  , ...
125                                                   []
128                                                   []
Name: small_text, Length: 88, dtype: object
user_data_50_95/rev_list_1079104-d.json
user_data_50_95/rev_list_1082583-d.json
user_data_50_95/rev_list_1082901-d.json
user_data_50_95/rev_list_1083270-d.json
user_data_50_95/rev_list_1084131-d.json
user_data_50_95/rev_list_1084847-d.json
User ID:  1084847
0         []
1         []
3         []
4         []
6     [may ]
9       [\n]
10        []
11        []
12        []
13      []]]
Name: small_text, dtype: object
user_data_50_95/rev_list_1223681-d.json
User ID:  1223681
1                                       []
2                                      [i]
3                                       []
4     [[[, ]], ]], [[, ]], [[, ]], [[, ]]]
7                                     [\n]
8                                       []
10                                    [\n]
11                                      []
12                                      []
13                                    [\n]
14                                      []
16                                      []
19                                      []
20                                      []
21                                      []
22                                      []
24                                      []
25                                      []
27                                      []
Name: small_text, dtype: object
user_data_50_95/rev_list_1390649-d.json
user_data_50_95/rev_list_1391544-d.json
User ID:  1391544
1                 [\n, +, 0, 0, 7||7]
2     [||, ''', [[, 3000, [[, ]], [[]
4                                  []
5                                  []
6                               [''']
                   ...
70                                [1]
72                                 []
73                        [17||, ''']
76                                 []
77                           [g, -07]
Name: small_text, Length: 68, dtype: object
user_data_50_95/rev_list_1392295-d.json
user_data_50_95/rev_list_1392968-d.json
User ID:  1392968
1                                          []
2     [ ,  ,  ,  ,  ,  ,  ,  ,  ,  ,  ,  ,  ]
3                                          []
6                              [[[, ]],  In ]
10                                         []
11                                        [e]
12                                     [mph ]
13                                        [n]
16                                         []
17                                        [E]
18                                       [\n]
Name: small_text, dtype: object
user_data_50_95/rev_list_1393869-d.json
User ID:  1393869
0     [\n]
1       []
4       []
5       []
6       []
7       []
8       []
9       []
10      []
11      []
Name: small_text, dtype: object
user_data_50_95/rev_list_1397872-d.json
user_data_50_95/rev_list_1398375-d.json
user_data_50_95/rev_list_1401727-d.json
user_data_50_95/rev_list_1403391-d.json
user_data_50_95/rev_list_1403430-d.json
user_data_50_95/rev_list_1404474-d.json
user_data_50_95/rev_list_1405465-d.json
user_data_50_95/rev_list_1405593-d.json
user_data_50_95/rev_list_1409009-d.json
user_data_50_95/rev_list_1409417-d.json
user_data_50_95/rev_list_1410759-d.json
user_data_50_95/rev_list_1411326-d.json
user_data_50_95/rev_list_1542182-d.json
user_data_50_95/rev_list_1543549-d.json
user_data_50_95/rev_list_1543752-d.json
user_data_50_95/rev_list_1681694-d.json
User ID:  1681694
0           [er]
1             []
2         [ and]
3             []
4             []
5     [ere, ies]
6             []
7             []
8             []
10            []
11            []
12            []
14           [i]
15            []
16            []
17            []
18      [[[, ]]]
19            []
20            []
21            []
Name: small_text, dtype: object
user_data_50_95/rev_list_1682296-d.json
user_data_50_95/rev_list_1683088-d.json
user_data_50_95/rev_list_1683383-d.json
User ID:  1683383
0                        []
2                        []
3                        []
4                        []
6                        []
8                        []
9                        []
10                   [t, t]
11    [s]], s]], s]], Gh}}]
13               [\n\n, \n]
Name: small_text, dtype: object
user_data_50_95/rev_list_1685625-d.json
User ID:  1685625
2           []
4           []
5           []
7           []
8         []]]
9          [s]
11          []
13          []
14         [£]
15          []
16          []
18          []
20    [[[, ]]]
21          []
22         [-]
23          []
24          []
25    [[[, ]]]
26         [ ]
27          []
28          []
30    [[[, ]]]
31          []
33          []
34         [ ]
35          []
36          []
37        [st]
38          []
39          []
40          []
41          []
43          []
44        [\n]
46          []
47          []
48          []
49          []
50          []
52         [l]
53         [o]
54          []
55          []
Name: small_text, dtype: object
user_data_50_95/rev_list_1686875-d.json
user_data_50_95/rev_list_1687521-d.json
user_data_50_95/rev_list_1687542-d.json
User ID:  1687542
0           []
1     [[[, [[]
2         [[[]
3         [[[]
4          [e]
5           []
7     [[[, ]]]
8           []
9           []
10          []
11          []
12          []
13          []
14          []
16          []
17          []
18          []
20          []
22          []
23          []
24          []
25          []
27        []]]
29          []
30          []
33         [l]
34         [ ]
35          []
36          []
39          []
44          []
46          []
48          []
50      [The ]
51          []
53          []
54          []
57          []
58          []
59          []
60         [.]
61       [ing]
63         [X]
64         [X]
65          []
66          []
67          []
70          []
71          []
73          []
74          []
75          []
77          []
79          []
81          []
82          []
83          []
85         [ ]
88         [l]
90    [[[, ]]]
Name: small_text, dtype: object
user_data_50_95/rev_list_1688026-d.json
user_data_50_95/rev_list_1688746-d.json
user_data_50_95/rev_list_1689015-d.json
user_data_50_95/rev_list_2122692-d.json
user_data_50_95/rev_list_2123903-d.json
User ID:  2123903
1                           []
2                           []
3                       [nstr]
4                           []
5                           []
6                           []
7                           []
8                           []
9                           []
10                          []
11                          []
12                          []
13                          []
14                         [ ]
15                          []
16                          []
17                          []
18                          []
19                          []
20                      [/www]
21                          []
22                      [.asp]
23    [ty, 1, ]], 9-20, 0, '']
24                          []
25                         [,]
26                          []
27            [[[, ]], [[, ]]]
Name: small_text, dtype: object
user_data_50_95/rev_list_2124599-d.json
User ID:  2124599
0                                                    []
1                                                    []
2      [ can, ., ', [[G, ]], [[, ]], [[, ]], [[, ]], c]
3                                                    []
4                            [[[, ]], l, l, ,, ,, ,, ,]
5                                                    []
6     [\n# A, \n# , '', '', \n# , #, \n# , [[, ]], [...
7                                                    []
8                                                  [si]
9                                                    []
10                                                   []
11                                                   []
12                                                   []
13                                                   []
14                                                   []
15                                                  [i]
16                                                   []
17                                                   []
18                                                   []
19                                                   []
20                                             [[[, [[]
21                                            [8, 8, i]
22                                                   []
23                                                   []
24                                                   []